# -*- coding: utf-8 -*-
"""Trabajo Uno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZy649pUBaPg82GZFZwSEyp0CFz3mSCF
"""



print("Hola Mundo!");

        nombre = input("Ingrese su nombre: ");
        print(f"Hola {nombre}!");

print("Coloque sus datos personales por favor");

nombre =input("Ingrese su nombre nuevamente: ");
apellido = input("Ingrese su apellido: ");
edad = input("Ingrese su edad en años: ");
lugar_de_residencia = input ("Ingrese su lugar de residencia: ");

print(f"Soy {nombre} {apellido}, tengo {edad} años y vivo en {lugar_de_residencia}.");

pi = 3.1416;
radio = float(input("Ingrese el radio del círculo en centímetros: "));

area = pi*(radio**2);
perimetro = 2*pi*radio;

print("El área del círculo es: ", area);
print("El perímetro del círculo es: ", perimetro);

segundos = int(input("Ingrese la cantidad de segundos que quiera pasar a horas: "));
horas = segundos/3600;

print(f"{segundos} segundos equivalen a {horas:.2f} horas");


numero = int(input("Ingrese el número del que desea connocer la tabla: "));

print(f"Tabla del {numero}");
for i in range(1, 11):
    print(f"{numero} x {i} = {numero * i}");

a = int(input("Ingrese el primer número (debe ser distinto de 0): "));
b = int(input("Ingrese el segundo número (debe ser distinto de 0): "));

print(f"Suma: {a + b}");
print(f"Multiplicación: {a * b}");
print(f"Resta: {a - b}");
print(f"División: {a / b}");

estatura = float(input("Ingrese su estatura en metros: "));
peso = float(input("Ingrese su peso en kilogramos: "));

imc = peso / (estatura ** 2)
print(f"Tu índice de masa corporal es de : {imc:.2f}");

grados_celsius = float(input("Ingrese los grados centígrados que desea pasar a Fahrenheit: "));
grados_fahrenheit = (9/5) * grados_celsius + 32;

print(f"{grados_celsius}°C equivalen a {grados_fahrenheit:.2f}°F");

num1 = float(input("Ingrese el primer número: "));
num2 = float(input("Ingrese el segundo número: "));
num3 = float(input("Ingrese el tercer número: "));

promedio = (num1 + num2 + num3) / 3;

print(f"El promedio de los tres números es: {promedio:.2f}");

